#include "gosh.h"

/**
 * gcmd_fork - a function that executes the fork syscall
 * @full_path: generated by the get_fullpath func.
 * the full path of the command to be forked.
 * @agv: the actual command entered
 * Return: execve on success, does not return.
 * the wait syscall waits for the child process to change state
 * the child process returns 0 , thay all return -1 on error
 */

int gcmd_fork(char *full_path, char **agv)
{
	pid_t gpid;
	int ret_stat;

	if (!full_path)
		return (-1);
	gpid = fork();
	if (gpid < 0)
		return (-1);
	if (!gpid)
	{
		if (execve(full_path, agv, NULL) < 0)
			return (-1);
	}
	else
	{
		wait(&ret_stat);
	}
	return (ret_stat);
}
